### ISSUE TITLE
We couldn't find the framework dependency = 'Microsoft.VCLibs.120.00.Phone.Debug' 

### ISSUE THREAD

**Issue by MohamedAKM** [Microsoft/steps#1]
<div style="margin-top: 20px; font-size: 14px; line-height: 20px; color: #333; font-weight: normal;">Validation errors</div> 

<div style="color:red;">4001: We couldn't find the framework dependency = 'Microsoft.VCLibs.120.00.Phone.Debug' with the specified version in the Store.</div> <br/>

![windowsphoneerror](https://cloud.githubusercontent.com/assets/11041896/6225595/9da7d58c-b69d-11e4-9f65-293dffd58838.PNG)

**Comment by ltomuta** [comment]
Don't submit Debug builds to the store

--- Original Message ---

**Comment by ParkerSM** [comment]
I do not! Just using some of the source code and add some references, and if I use the source I mentioned that at the app.
